###
GET http://localhost:5000/dataSummary

###
POST http://localhost:5000/data
Content-Type: application/json

{
    "sumber": "ME",
    "timestamp": "{{$localDatetime rfc1123|iso8601}}",
    "app_name":"MyCX",
    "pengukuran":"RTS",
    "value":"",
    "unit":"",
    "satuan":"",
    "status":"",
    "status_reading":""
}